### ISSUE TITLE
I have hundreds of IP addresses that need to be monitored using MTR.

### ISSUE THREAD

**Issue by aliuzzz** [mgumz/mtr-exporter#14]
I checked the example in the helper, which means adding hundreds of ports directly to prometheus.yml? How should I write configuration files

**Comment by aliuzzz** [comment]
prometheus.yml
global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "mtr-example.com"
    static_configs:
    - targets: ["localhost:8080"]
  - job_name: "mtr-golang.org"
    static_configs:
    - targets: ["localhost:8081"]
  - job_name: "mtr-prometheus.io"
    static_configs:
    - targets: ["localhost:8082"]
  - job_name: "mtr-www.bitwizard.nl"
    static_configs:
    - targets: ["localhost:8083"]
  I don't monitor specific IPs through MTR, so my job_ Does name write the IP address I want to monitor? If I have 100 IPs, I need to write 100 job names？

**Comment by mgumz** [comment]
Use https://github.com/mgumz/mtr-exporter/#jobs-file-syntax to provide 1 job file with 100 lines on it.

Then you have to configure your prometheus instance to scrape only 1 mtr-exporter instance.

If you spin up 100 mtr-exporter instances than you have to tell those 100 mtr-exporter instances to prometheus. Or you use something like kubernetes and the prometheus-operator to do that automatically.

**Comment by aliuzzz** [comment]
ok,tks.
i will try it
