### ISSUE TITLE
Docker image

### ISSUE THREAD

**Issue by Bart-Westenenk** [mgumz/mtr-exporter#15]
Hello,
Is there a docker image available for this project? I see that there is a Dockerfile.
Would it be possible for you to add a github workflow to also publish this docker image?

Thank you in advance!

**Comment by mgumz** [comment]
@Bart-Westenenk feel free to provide a PR on that.

**Comment by mgumz** [comment]
https://github.com/mgumz/mtr-exporter/pkgs/container/mtr-exporter
