### ISSUE TITLE
Json parse issue

### ISSUE THREAD

**Issue by diego-tironi** [mgumz/mtr-exporter#9]
root@linux# ./mtr-exporter -bind 192.168.0.150:8080 -mtr /root/mtr-0.92/mtr -- 8.8.8.8
serving /metrics at 192.168.0.150:8080 ...
launching /root/mtr-0.92/mtr -j 8.8.8.8
failed: json: cannot unmarshal string into Go struct field mtrMtr.report.mtr.tos of type int64

If I launch mtr manually, the output is:
{
  "report": {
    "mtr": {
      "src": "influx",
      "dst": "8.8.8.8",
      "tos": "0x0",
      "psize": "64",
      "bitpattern": "0x00",
      "tests": "10"
    },
    "hubs": [{
      "count": "1",
      "host": "192.168.0.1",
      "Loss%": 0.00,
      "Snt": 10,
      "Last": 0.57,
      "Avg": 0.62,
      "Best": 0.53,
      "Wrst": 0.74,
      "StDev": 0.07
    },
...

Any clues?

**Comment by mgumz** [comment]
@diego-tironi which version of `mtr` do you have installed on your system to produce the output (`mtr`, not `mtr-exporter`).

in general, i wonder why `mtr` would yield both .tos and .tests now as strings (while the content are numbers). maybe they have change the format underneath a bit.

**Comment by mgumz** [comment]
@diego-tironi aaah, it looks like that behaviour was introduced in mtr:0.94 ~ 2020: https://github.com/traviscross/mtr/pull/355 … which led to https://github.com/mgumz/mtr-exporter/commit/15cfd19c6205ad7dc7af7b57761e670550d092e8 in the past.

so, your mtr version smells like the old flavour.

**Comment by diego-tironi** [comment]
@mgumz bingo! I compiled the last version of mtr (with jansson support) from the git repository and the issue went away.
Thank you very much!

**Comment by mgumz** [comment]
Because some other people also went into this … not so obvious … trap: 39711bfe7298b951abdd682aa1edf4ab83361d80
